### PR TITLE
Updated floating2D.py and MeshRefinement.py

### PR DESCRIPTION
**Pull request by acatwithacomputer**
It seems as if there were a few changes to ChRigidBody and py2gmsh in the last year since the test case was made, so it wouldn't run. It should run now.

### CODE REVIEW

**Comment by tridelat** [comment]
@acatwithacomputer for py2gmsh, it has been modified so that it is not necessary to use a MeshRefinement.py file, the function `py2gmsh.Mesh.geometry2mesh(...)` allows you to convert the proteus geometry to a `Mesh` directly, so replacing the call to MeshRefinement and removing MeshRefinement.py should be safe.

**Comment by acatwithacomputer** [comment]
@tridelat Ah, I see. I made the changes to floating2D and removed MeshRefinement.

**Comment by adimako** [comment]
@acatwithacomputer You are about to merge something in air-water-vv. Have you done a test to see that it does not break anything in the proteus automated test. You can do this by creating / forking a branch from master proteus branch and changing the gitmodule to point to your branch, rather than the master. 
https://github.com/erdc/proteus/blob/master/.gitmodules#L4

**Comment by acatwithacomputer** [comment]
@adimako If I've understood you correctly, yes. I've run `make develop` and `make test` with no errors save one import error in proteus/tests/griffiths_lane_6/test_griffiths_lane6.py, but I get that error whether on the master branch of air-water-vv or this one.

**Pull request merged**
